#pragma once


// 21 이상부터 시작해야 한다!!!
enum class PACKET_ID : short
{
	LOGIN_REQ = 21,
	LOGIN_RES = 22,

	LOBBY_LIST_REQ = 26,
	LOBBY_LIST_RES = 27,

	LOBBY_ENTER_REQ = 31,
	LOBBY_ENTER_RES = 32,

	LOBBY_LEAVE_REQ = 46,
	LOBBY_LEAVE_RES = 47,

	ROOM_ENTER_REQ = 61,
	ROOM_ENTER_RES = 62,
	ROOM_NEW_USER_NTF = 63,
	ROOM_USER_LIST_NTF = 64,

	ROOM_LEAVE_REQ = 66,
	ROOM_LEAVE_RES = 67,
	ROOM_LEAVE_USER_NTF = 68,

	ROOM_CHAT_REQ = 76,
	ROOM_CHAT_RES = 77,
	ROOM_CHAT_NOTIFY = 78,

	MAX = 256
};

